
@startuml Appointment massage (GET ALL)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Appointment massage (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:massages" as routerMassages
participant "<<controllers>>\n:massages" as controllersMassages
participant "<<model>>\n:Massage" as modelMassage
database "<<MongoDB>>\n:massages" as MassagesDatabase

client->server ++:req.put('/massages')
server->routerMassages ++:app.use('/massages',massages)
routerMassages -> controllersMassages ++:getMassages()
controllersMassages->modelMassage ++:find()
modelMassage ->MassagesDatabase ++: MassageSchema
MassagesDatabase --> modelMassage --: massage
controllersMassages <-- modelMassage --:massage
controllersMassages->client --:response

@enduml