
@startuml Manage massage (GET one)

header Massage Sequence Diagram
footer Page %page% of %lastpage%
title "Managet massage (GET one)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:massages" as routerMassages
participant "<<controllers>>\n:massages" as controllersMassages
participant "<<model>>\n:Massage" as modelMassage
database "<<MongoDB>>\n:massages" as MassagesDatabase

client->server ++:req.put('/massages/:id')
server->routerMassages ++:app.use('/massages',massages)
routerMassages -> controllersMassages ++:getMassage()
controllersMassages->modelMassage ++:findById(req.params.id)
modelMassage ->MassagesDatabase ++: MassageSchema
MassagesDatabase --> modelMassage --: massage
controllersMassages <-- modelMassage --:massage
controllersMassages->client --:response

@enduml